language: python
python:
  - "2.7"

script:
  - python setup.py build install
  - genomon_pa --version
  - pwd

notifications:
  emails:
    - aiokada@hgc.jp
  on_success: change
  on_failure: always
