#! /usr/bin/env python
# -*- coding: utf-8 -*-
"""
Created on Wed Dec 02 17:43:52 2015

@author: okada
"""

def main():
    import genomon_post_analysis.run
    genomon_post_analysis.run.main()

if __name__ == "__main__":
    main()
    
